name: Push libretranslate v1.3.2 to ECR

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/push-libretranslate-v1_3_2.yml'

jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_IMAGE: libretranslate/libretranslate:v1.3.2
      DEST_TAG: v1.3.2

    steps:
      - name: Checkout (no source needed, but keeps workspace sane)
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: (Optional) Login to Docker Hub to avoid rate limits
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Ensure ECR repository exists
        env:
          REPO: ${{ secrets.ECR_REPO_LIBRE }}   # e.g. libretranslate
        run: |
          aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$REPO" >/dev/null

      - name: Pull upstream image
        run: |
          docker pull "${UPSTREAM_IMAGE}"

      - name: Retag & Push to ECR
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY }} # e.g. 257976284139.dkr.ecr.ap-northeast-2.amazonaws.com
          REPO:     ${{ secrets.ECR_REPO_LIBRE }} # e.g. libretranslate
        run: |
          DEST_IMAGE="$REGISTRY/$REPO:${DEST_TAG}"
          docker tag "${UPSTREAM_IMAGE}" "$DEST_IMAGE"
          docker push "$DEST_IMAGE"
          echo "DEST_IMAGE=$DEST_IMAGE" >> $GITHUB_ENV

      - name: Print pushed digest (for pinning in ECS)
        env:
          REPO: ${{ secrets.ECR_REPO_LIBRE }}
        run: |
          DIGEST=$(aws ecr describe-images \
            --repository-name "$REPO" \
            --image-ids imageTag="${DEST_TAG}" \
            --query 'imageDetails[0].imageDigest' --output text)
          echo "ECR Image: ${{ env.DEST_IMAGE }}@${DIGEST}"
